#!/usr/bin/env bash

#
# Install git hooks.
#

main() {
  local hooks_path="$1"
  local hooks_path_default='.dotfiles/hooks'
  local fail=0

  [ -z "$hooks_path" ] && hooks_path="$hooks_path_default"

  if [ -n "$CI" ]; then
    echo 'CI detected. No hooks installed.'
    return 0
  fi

  git config --local core.hooksPath "$hooks_path"
}
