#!/usr/bin/env bash

#
# Visual Studio Code.
#

install() {
  echo 'No vscode installer available.'
}

configure() {
  local configure_path="$1"
  local configure_path_osx="$HOME/Library/Application Support/Code/User"
  local configure_path_linux="$HOME/.config/Code/User"
  local backup_path="$2"
  local backup_path_default="."
  local source_path

  source_path="$HOME/.dotfiles/$(dirname "$0")"

  [ -z "$backup_path" ] && backup_path="$backup_path_default"
  mkdir -p "$backup_path"

  if [ "$(uname)" == 'Darwin' ]; then
    [ -d "$configure_path" ] || configure_path="$configure_path_osx"
  elif [ "$(uname)" == 'Linux' ]; then
    [ -d "$configure_path" ] || configure_path="$configure_path_linux"
  fi

  if [ -z "$configure_path" ]; then
    echo 'Error. Configuration path argument not given.'
    return 1
  fi

  # User settings.
    [ -L "$configure_path/settings.json" ] && unlink "$configure_path/settings.json"

    [ -d "$configure_path/settings.json" ] && mv "$configure_path/settings.json" "$backup_path/settings.json.backup"

    ln -sv "$source_path/settings.json" "$configure_path"

  # Snippets.
    [ -L "$configure_path/snippets" ] && unlink "$configure_path/snippets"

    [ -d "$configure_path/snippets.backup" ] && mv "$configure_path/snippets.backup" "$backup_path/snippets.backup"

    ln -sv "$source_path/snippets" "$configure_path"

  # Key bindings.
    [ -L "$configure_path/keybindings.json" ] && unlink "$configure_path/keybindings.json"

    [ -d "$configure_path/keybindings.json" ] && mv "$configure_path/keybindings.json" "$backup_path/keybindings.json.backup"

    ln -sv "$source_path/keybindings.json" "$configure_path"

}

configure "$1" "$2"
