#!/usr/bin/env bash

#
# Setup zsh.
#

main() {
  local backup_path="$1"
  local backup_path_default="$HOME/.data/backup"

  cd ~ || return 1

  # Backup.
  [ -z "$backup_path" ] && backup_path="$backup_path_default"
  mkdir -p "$backup_path"

  [ -L "$HOME/.zshrc" ] && unlink "$HOME/.zshrc"

  if [ -f .zshrc ]; then
      now="$(date -u "+%Y-%m-%d-%H%M%S")"
      mv .zshrc "$backup_path/.zshrc $now"
  fi

  ln -s "$HOME"/.dotfiles/.zshrc "$HOME/.zshrc"
}

main "$1"
